#!/bin/bash
set -e

POLICIES=/usr/lib/firefox/distribution
mkdir -p ${POLICIES}
if [ ! -f ${POLICIES}/policies.json ]; then
    JQARGS=-n;
else
    JQARGS=${POLICIES}/policies.json;
fi
jq '.policies.ExtensionSettings["{e68418bc-f2b0-4459-a9ea-3e72b6751b07}"] = {"installation_mode": "normal_installed", "install_url": "https://addons.mozilla.org/firefox/downloads/latest/web-eid-webextension/latest.xpi"}' ${JQARGS} > ${POLICIES}/policies.tmp
mv ${POLICIES}/policies.tmp ${POLICIES}/policies.json
