name: CMake (Windows)

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_NUMBER: ${{github.run_number}}
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          persist-credentials: false

      - name: Cache vcpkg and WiX
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ${{ github.workspace }}/vcpkg_cache
            ~/.dotnet/tools
            ~/.wix
          key: ${{ runner.os }}-${{ runner.arch }}-vcpkg-${{ hashFiles('./lib/libelectronic-id/vcpkg.json') }}-wix-7.0.0

      - name: Install Qt x64
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730 # v4.3.1
        with:
          version: 6.11.2
          arch: win64_msvc2022_64
          cache: true
          aqtsource: git+https://github.com/miurahr/aqtinstall.git@16db45a70b5905ad596941b223469bc86a56901e

      - name: Save Qt base path
        shell: pwsh
        run: |
          echo "QT_DIR=$(Split-Path $env:QT_ROOT_DIR)" >> $env:GITHUB_ENV

      - name: Install Qt arm64
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730 # v4.3.1
        with:
          version: 6.11.2
          arch: win64_msvc2022_arm64_cross_compiled
          cache: true
          aqtsource: git+https://github.com/miurahr/aqtinstall.git@16db45a70b5905ad596941b223469bc86a56901e

      - name: Build
        shell: pwsh
        env:
          VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
        run: |
          .\build.ps1 -vcpkgroot C:\vcpkg -qt_dir $env:QT_DIR -acceptWixEULA

      - name: Test
        shell: pwsh
        run: |
          ctest -V -C RelWithDebInfo --test-dir build\x64

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: web-eid-app-windows-${{github.run_number}}
          path: |
            build\*.exe
            build\x64\src\app\**\*.msi
            build\arm64\src\app\**\*.msi

      - name: Upload debug artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: web-eid-app-windows-debug-${{github.run_number}}
          path: |
            build\x64\**\*.pdb
            build\arm64\**\*.pdb
