name: CMake (Windows)

on: [push, pull_request]

env:
  BUILD_NUMBER: ${{github.run_number}}
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false

      - name: Cache vcpkg
        uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/vcpkg_cache
            ~/.dotnet/tools
            ~/.wix
          key: vcpkg-${{ hashFiles('./lib/libelectronic-id/vcpkg.json') }}

      - name: Install Qt x64
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.11.1
          arch: win64_msvc2022_64
          cache: true
          aqtsource: git+https://github.com/miurahr/aqtinstall.git

      - name: Save Qt base path
        shell: pwsh
        run: |
          echo "QT_DIR=$(Split-Path $env:QT_ROOT_DIR)" >> $env:GITHUB_ENV

      - name: Install Qt arm64
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.11.1
          arch: win64_msvc2022_arm64_cross_compiled
          cache: true
          aqtsource: git+https://github.com/miurahr/aqtinstall.git

      - name: Build
        shell: pwsh
        env:
          VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
        run: |
          .\build.ps1 -vcpkgroot C:\vcpkg -qt_dir $env:QT_DIR
          cmake --install build/x64/sbom
          cmake --install build/arm64/sbom

      - name: Test
        shell: pwsh
        run: |
          $env:QT_QPA_PLATFORM = 'offscreen'
          ctest -V -C RelWithDebInfo --test-dir build\x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: web-eid-app-windows-${{github.run_number}}
          path: |
            build\*.exe
            build\x64\src\app\**\*.msi
            build\arm64\src\app\**\*.msi

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v7
        with:
          name: web-eid-app-windows-sbom-${{matrix.arch}}-${{github.run_number}}
          path: build/*.spdx

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v7
        with:
          name: web-eid-app-windows-debug-${{github.run_number}}
          path: |
            build\x64\**\*.pdb
            build\arm64\**\*.pdb
