name: CMake (Ubuntu Linux)

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo
  BUILD_NUMBER: ${{github.run_number}}
  QT_QPA_PLATFORM: offscreen
  DEBIAN_FRONTEND: noninteractive
  DEBFULLNAME: GitHub build
  DEBEMAIL: github-action@github.com
  CMAKE_BUILD_PARALLEL_LEVEL: 3

jobs:
  build:
    runs-on: ubuntu-24.04${{ matrix.arch == 'arm64' && '-arm' || '' }}
    container: ubuntu:${{matrix.container}}
    strategy:
      matrix:
        container: ['22.04', '24.04', '24.10', '25.04']
        arch: ['amd64', 'arm64']

    steps:
      - name: Install dependencies
        run: apt update -qq && apt install --no-install-recommends -y git lsb-release fakeroot build-essential devscripts debhelper lintian pkg-config cmake libpcsclite-dev libssl-dev libgtest-dev libgl-dev libqt6svg6-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build -S .

      - name: Build
        run: |
          cmake --build build --config $BUILD_TYPE --target installer
          # Debian creates artifacts outside of project dir, copy them back to make them available in the build artifacts
          mv ../web-eid*.* build/

      - name: Test package
        run: lintian build/*.deb

      - uses: actions/upload-artifact@v4
        with:
          name: web-eid-app-ubuntu-build-ubuntu${{matrix.container}}-${{ matrix.arch }}-${{github.run_number}}
          path: build/*.*deb
